In [2]:
# test
import pandas as pd
test = {'a':5, 'b':6,'c':7,'d':8,'e':9}
df = pd.DataFrame(test, index=[0,1,2,3,4])
df

   a  b  c  d  e
0  5  6  7  8  9
1  5  6  7  8  9
2  5  6  7  8  9
3  5  6  7  8  9
4  5  6  7  8  9

In [8]:
df['a']+df['c']

0    12
1    12
2    12
3    12
4    12
dtype: int64

In [9]:
import csv
site_dict = {}
with open('fastq_data/sites.csv') as rf:
    csv_reader = csv.reader(rf)
    for row in csv_reader:
        site = row[1]
        name = row[0]
        if site in site_dict:
            site_dict[site].append(name)
        else:
            site_dict[site] = [name]
print(site_dict)

{'BEARDY': ['M22-20124-0001', 'M22-20124-0002', 'M22-20124-0003'], 'BEDWELL': ['M22-20124-0004', 'M22-20124-0005', 'M22-20124-0006'], 'CONTROL3879-1122-EC': ['M22-20124-0007'], 'BEES': ['M22-20124-0008', 'M22-20124-0009', 'M22-20124-0010'], 'BELLANBOE': ['M22-20124-0011', 'M22-20124-0012', 'M22-20124-0013'], 'BENBERN': ['M22-20124-0014', 'M22-20124-0015', 'M22-20124-0016'], 'BENBRAGGIE': ['M22-20124-0017', 'M22-20124-0018', 'M22-20124-0019'], 'BEREEN': ['M22-20124-0020', 'M22-20124-0021', 'M22-20124-0022'], 'BIG4': ['M22-20124-0023', 'M22-20124-0024', 'M22-20124-0025'], 'BOLIVIA': ['M22-20124-0026', 'M22-20124-0027', 'M22-20124-0028'], 'BONSHAW': ['M22-20124-0029', 'M22-20124-0030', 'M22-20124-0031'], 'CAROONA': ['M22-20124-0032', 'M22-20124-0033', 'M22-20124-0034'], 'CLERKNESS': ['M22-20124-0035', 'M22-20124-0036']}

In [14]:
df = pd.read_csv('qiime2/loci/asvs/asv_count_tax_seqs_summary.csv')
df.head()

,Taxon,EXTC-1,M22-09276-0009,M22-09276-0011,M22-10871-0001,M22-10871-0002,M22-10871-0003,M22-10871-0004,M22-20124-0001,M22-20124-0002,...,M23-03493-0007,M23-03493-0008,M23-03493-0009,M23-03493-0010,M23-03493-0011,M23-03493-0012,NTC,Taxa_confidence,Reference_variants,reference_sequence
0,k__Eukaryota_2759;p__Chordata_7711,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,111.0,0.0,0.0,10.0,0.0,0.0,19.0,0.984767,6,GGGCGATCCGATTGAAGCCCATTATCGCCGCAAAACTCCTCCCAAA...
1,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,2910.0,77.0,147.0,0.0,657.0,0.0,0.0,0.0,0.0,...,0.0,344.0,0.0,0.0,0.0,0.0,0.0,0.967559,9,CCCCAAGCCTAGCACTAACTGTTTAATAAAATGTAATAAATGCAAA...
2,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,873.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.999998,1,CCTCGAAAAATAATAAAGACAATTAATAAAACAATAAAAACAAGAA...
3,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.986173,1,CCCCAAGCTTAAAACCTGTCTTTAACTAAAAAGCTAAACGAGCAAA...
4,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,224.0,0.0,0.0,0.0,0.0,0.0,1.000000,1,CCCCAAGTTTACGATTCATTTTACATAAAGAACTAAACAAACAAAG...

In [18]:
for site in site_dict:
    print(samples)
    samples = site_dict[site]
    # across cols
    df[site] = df[samples].sum(axis=1)
    # now get rid of the old columns
    df.drop(samples, axis=1, inplace=True)
df.head()

['M22-20124-0035', 'M22-20124-0036']
['M22-20124-0001', 'M22-20124-0002', 'M22-20124-0003']
['M22-20124-0004', 'M22-20124-0005', 'M22-20124-0006']
['M22-20124-0007']
['M22-20124-0008', 'M22-20124-0009', 'M22-20124-0010']
['M22-20124-0011', 'M22-20124-0012', 'M22-20124-0013']
['M22-20124-0014', 'M22-20124-0015', 'M22-20124-0016']
['M22-20124-0017', 'M22-20124-0018', 'M22-20124-0019']
['M22-20124-0020', 'M22-20124-0021', 'M22-20124-0022']
['M22-20124-0023', 'M22-20124-0024', 'M22-20124-0025']
['M22-20124-0026', 'M22-20124-0027', 'M22-20124-0028']
['M22-20124-0029', 'M22-20124-0030', 'M22-20124-0031']
['M22-20124-0032', 'M22-20124-0033', 'M22-20124-0034']

,Taxon,EXTC-1,M22-09276-0009,M22-09276-0011,M22-10871-0001,M22-10871-0002,M22-10871-0003,M22-10871-0004,M23-03493-0001,M23-03493-0002,...,BEES,BELLANBOE,BENBERN,BENBRAGGIE,BEREEN,BIG4,BOLIVIA,BONSHAW,CAROONA,CLERKNESS
0,k__Eukaryota_2759;p__Chordata_7711,0.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,631.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
1,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,2910.0,77.0,147.0,0.0,657.0,0.0,0.0,0.0,0.0,...,0.0,2413.0,878.0,1075.0,19157.0,2813.0,258.0,146.0,1913.0,7372.0
2,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,873.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
4,k__Eukaryota_2759;p__Chordata_7711;c__Actinopt...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,445.0,0.0,1150.0,0.0,0.0,0.0,12.0,0.0,0.0

In [19]:
df.to_csv('qiime2/loci/asvs/asv_count_tax_seqs_summary_sites.csv', index=False)